apiVersion: v1
kind: Service
metadata:
  name: ferrix-forwarder-client-service
  labels:
    app.kubernetes.io/name: ferrix-forwarder-client-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app.kubernetes.io/name: ferrix-forwarder-client