name: docker
 
on:
 push:
   paths:
      - '**/Dockerfile'
      - '**.go'
      - '.github/workflows/docker.yml'
      - '**/go.mod'
      - '**/go.sum'
   branches: [main]
 
jobs:
 docker:
   runs-on: ubuntu-latest
   permissions:
      packages: write
   strategy:
     matrix:
       component: [server, client, forwarder]
   steps:
     -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v3
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     -
       name: Checkout repository
       uses: actions/checkout@v4
     - 
       name: Log in to the Github Container registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - 
       name: Cache Docker layers
       uses: actions/cache@v3
       with:
         path: /tmp/.buildx-cache
         key: ${{ runner.os }}-buildx-${{ matrix.component }}-${{ github.sha }}
         restore-keys: |
           ${{ runner.os }}-buildx-${{ matrix.component }}-
     - 
       name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@v5
       with:
         images: ghcr.io/${{ github.repository }}-${{ matrix.component }}
     -
       name: Build and push
       uses: docker/build-push-action@v6
       with:
         context: ./${{ matrix.component }}
         file: ./${{ matrix.component }}/Dockerfile
         platforms: linux/amd64,linux/arm64,linux/arm/v7
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         cache-from: type=local,src=/tmp/.buildx-cache
         cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
     - 
       # Temp fix
       # https://github.com/docker/build-push-action/issues/252
       # https://github.com/moby/buildkit/issues/1896
       name: Move cache
       run: |
         rm -rf /tmp/.buildx-cache
         mv /tmp/.buildx-cache-new /tmp/.buildx-cache
